"""empty message

Revision ID: e9762be90aef
Revises: 
Create Date: 2022-06-09 12:05:41.765895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9762be90aef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administrador',
    sa.Column('idAdminsitrador', sa.Integer(), nullable=False),
    sa.Column('correoElectronico', sa.String(length=100), nullable=False),
    sa.Column('contrasenia', sa.String(length=50), nullable=False),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('idAdminsitrador')
    )
    op.create_table('Cafeteria',
    sa.Column('idCafeteria', sa.Integer(), nullable=False),
    sa.Column('nombreCafeteria', sa.String(length=80), nullable=False),
    sa.Column('facultadPerteneciente', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('horaInicio', sa.String(length=10), nullable=False),
    sa.Column('horaFin', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idCafeteria')
    )
    op.create_table('Consumidor',
    sa.Column('idConsumidor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('correoElectronico', sa.String(length=100), nullable=False),
    sa.Column('contrasenia', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idConsumidor')
    )
    op.create_table('PersonalCafeteria',
    sa.Column('idPersonal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('CURP', sa.String(length=18), nullable=False),
    sa.Column('correoElectronico', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.Column('idCafeteria', sa.Integer(), nullable=False),
    sa.Column('contrasenia', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idPersonal')
    )
    op.create_table('Producto',
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('tiempoAproximado', sa.Integer(), nullable=False),
    sa.Column('rutaImagen', sa.BLOB(), nullable=False),
    sa.Column('idCafeteria', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idProducto')
    )
    op.create_table('ReseñaCafeteria',
    sa.Column('idReseña', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('opinion', sa.String(length=500), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('rutaImagen', sa.BLOB(), nullable=True),
    sa.Column('idCafeteria', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idReseña')
    )
    op.create_table('ReseñaProducto',
    sa.Column('idReseña', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('opinion', sa.String(length=500), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('rutaImagen', sa.BLOB(), nullable=True),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idReseña')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReseñaProducto')
    op.drop_table('ReseñaCafeteria')
    op.drop_table('Producto')
    op.drop_table('PersonalCafeteria')
    op.drop_table('Consumidor')
    op.drop_table('Cafeteria')
    op.drop_table('Administrador')
    # ### end Alembic commands ###
